In [16]:
import numpy as np
import pandas as pd

In [17]:
data = np.array([[5, 12, 18, 23, 45],
                 [7, 14, 22, 31, 50],
                 [10, 15, 25, 35, 55],
                 [13, 20, 30, 40, 60]])

print("Dizinin Boyutu:", data.shape)
print("Dizinin Veri Türü:", data.dtype)


Dizinin Boyutu: (4, 5)
Dizinin Veri Türü: int64


In [18]:
column_means = np.mean(data, axis=0)
print("Her bir sütunun ortalamaları:", column_means)

Her bir sütunun ortalamaları: [ 8.75 15.25 23.75 32.25 52.5 ]


In [19]:
row_max = np.max(data, axis=1)
print("Her bir satırdaki maksimum değerler:", row_max)

Her bir satırdaki maksimum değerler: [45 50 55 60]


In [20]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("handanvural/verinumpy")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/verinumpy


In [21]:
np.savetxt("veri.csv", data, delimiter=",", fmt="%d")

In [22]:
loaded_data = np.loadtxt("veri.csv", delimiter=",")
print("CSV'den okunan veri:\n", loaded_data)

CSV'den okunan veri:
 [[ 5. 12. 18. 23. 45.]
 [ 7. 14. 22. 31. 50.]
 [10. 15. 25. 35. 55.]
 [13. 20. 30. 40. 60.]]
